fix: ensure getPaginatedData is defined
This addresses:

```
Run npm run gh-contributions

> feeder@0.0.4 gh-contributions
> node fetch-github-contributions.js

file:///home/runner/work/feeder/feeder/fetch-github-contributions.js:7
getPaginatedData = async () => {
                 ^

ReferenceError: getPaginatedData is not defined
```

Signed-off-by: Mike Ball <mikedball@gmail.com>